"""
app/services/rule_engine.py — Business Knowledge Loader

Loads from config/ folder:
  - config/rules/kpi_definitions.json  → KPI formulas & column mappings
  - config/rules/drill_down_hierarchy.json → Dimension hierarchies
  - config/business_rules.yml          → 18 predefined rules + new_rules section
  - config/ml_config.yml               → ML thresholds

New rules generated by the Knowledge Update Tool are stored in
config/business_rules.yml under the `new_rules` key.
"""

import ast
import json
import logging
import re
import yaml
from pathlib import Path

from app.config import (
    KPI_DEFINITIONS_PATH, DRILL_DOWN_HIERARCHY_PATH,
    PREDEFINED_RULES, KPI_THRESHOLDS, VARIANCE_DRIVERS,
    FLAG_DECODING, NEW_RULES, SUPPORTED_OPS,
    BUSINESS_RULES_YAML_PATH,
)

logger = logging.getLogger(__name__)

# business_rules.yml conditions use uppercase AND/OR/NOT (not valid Python
# keywords) — normalize case before parsing. Word-boundary so this never
# touches identifiers that happen to contain "and"/"or"/"not" as a substring.
_BOOL_KEYWORD_RE = re.compile(r"\b(AND|OR|NOT)\b", re.IGNORECASE)

# Only these AST node types are allowed in a rule condition after
# evaluate_rules() has substituted in the actual KPI value — pure numeric
# comparison/boolean/arithmetic expressions plus abs(). Anything else
# (Name other than "abs", Attribute, Subscript, Lambda, comprehensions,
# calls to anything but abs, ...) is rejected rather than evaluated.
_ALLOWED_NODES = (
    ast.Expression, ast.Compare, ast.BoolOp, ast.And, ast.Or, ast.Not,
    ast.UnaryOp, ast.USub, ast.UAdd, ast.BinOp, ast.Add, ast.Sub, ast.Mult,
    ast.Div, ast.Constant, ast.Load,
    ast.Gt, ast.Lt, ast.GtE, ast.LtE, ast.Eq, ast.NotEq,
)


def _safe_eval(expr: str) -> bool:
    """
    Evaluate a business-rule condition (post value-substitution — pure
    numeric comparisons/booleans/arithmetic plus abs()) without Python's
    eval(). Raises ValueError on anything outside that grammar, including
    attempted sandbox escapes — callers should catch and skip the rule,
    exactly as a malformed condition is skipped today.
    """
    normalized = _BOOL_KEYWORD_RE.sub(lambda m: m.group(1).lower(), expr)
    tree = ast.parse(normalized, mode="eval")

    # A rule condition must itself be boolean-producing — reject a bare
    # value/identifier (e.g. just "abs") slipping through the node walk
    # below as a technically-allowed but meaningless top-level expression.
    if not isinstance(tree.body, (ast.Compare, ast.BoolOp, ast.UnaryOp)):
        raise ValueError(f"Rule condition is not a boolean expression: {expr!r}")

    for node in ast.walk(tree):
        if isinstance(node, ast.Call):
            if not (isinstance(node.func, ast.Name) and node.func.id == "abs"
                    and not node.keywords):
                raise ValueError(f"Disallowed call in rule condition: {expr!r}")
            continue
        if isinstance(node, ast.Name):
            # Only reachable as the callee of an already-validated abs(...)
            # call above — any other Name (bare identifier) is disallowed.
            if node.id != "abs":
                raise ValueError(f"Disallowed identifier in rule condition: {expr!r}")
            continue
        if not isinstance(node, _ALLOWED_NODES):
            raise ValueError(f"Disallowed expression in rule condition: {expr!r}")

    return bool(eval(compile(tree, "<rule_condition>", "eval"), {"__builtins__": {"abs": abs}}, {}))


class RuleEngine:
    """
    Loads and exposes business knowledge:
    - KPI definitions & formulas (from JSON)
    - 18 predefined insurance business rules (from YAML)
    - KPI thresholds (from YAML)
    - Variance driver definitions (from YAML)
    - Drill-down dimension hierarchies (from JSON)
    - New rules added dynamically (stored back in YAML)
    """

    def __init__(
        self,
        kpi_definitions_path: str | Path | None = None,
        hierarchy_path: str | Path | None = None,
        business_rules_path: str | Path | None = None,
    ):
        """Agent 3 redesign, Phase 2 (plan "zany-giggling-crayon") — these
        paths used to be fixed module-level imports; now they're
        constructor params, defaulting to the exact same app.config-sourced
        paths/pre-parsed values (Insurance's content, unchanged) when not
        overridden, so every existing caller (RuleEngine()) behaves
        byte-identically. A domain plugin supplies its own paths to reuse
        this class's loader/lookup/eval mechanics for a different domain.
        """
        self._kpi_definitions_path = Path(kpi_definitions_path) if kpi_definitions_path else KPI_DEFINITIONS_PATH
        self._hierarchy_path = Path(hierarchy_path) if hierarchy_path else DRILL_DOWN_HIERARCHY_PATH
        self._business_rules_path = Path(business_rules_path) if business_rules_path else BUSINESS_RULES_YAML_PATH

        if kpi_definitions_path or hierarchy_path or business_rules_path:
            # A domain plugin supplied at least one override — load fresh
            # from the (possibly custom) paths rather than reusing the
            # app-startup-time pre-parsed globals below, which were parsed
            # from the default Insurance paths only.
            self._kpis = self._load_json(self._kpi_definitions_path).get("kpis", {})
            self._hierarchy = self._load_json(self._hierarchy_path)
            rules_config = self._load_yaml_file(self._business_rules_path)
            self._predefined_rules = list(rules_config.get("predefined_rules", []))
            self._new_rules = list(rules_config.get("new_rules", []))
            self._thresholds = dict(rules_config.get("thresholds", {}))
            self._variance_drivers = dict(rules_config.get("variance_drivers", {}))
            self._flag_decoding = dict(rules_config.get("flags", {}))
            self._supported_ops = list(rules_config.get("supported_operations", []))
        else:
            self._kpis            = self._load_json(KPI_DEFINITIONS_PATH).get("kpis", {})
            self._hierarchy       = self._load_json(DRILL_DOWN_HIERARCHY_PATH)
            self._predefined_rules= list(PREDEFINED_RULES)
            self._new_rules       = list(NEW_RULES)
            self._thresholds      = dict(KPI_THRESHOLDS)
            self._variance_drivers= dict(VARIANCE_DRIVERS)
            self._flag_decoding   = dict(FLAG_DECODING)
            self._supported_ops   = list(SUPPORTED_OPS)

        # Validate loaded configurations using Pydantic
        self._validate_configs()

        logger.info(
            f"Rule Engine loaded: {len(self._kpis)} KPIs, "
            f"{len(self._predefined_rules)} predefined rules, "
            f"{len(self._new_rules)} dynamic rules"
        )

    def _validate_configs(self):
        """Validates all loaded configuration data via Pydantic schemas."""
        from app.services.schemas import KPIDefinitionsRoot, BusinessRulesRoot
        try:
            # Reconstruct the raw KPI dict wrapper to validate
            raw_kpi_data = {"kpis": self._kpis}
            KPIDefinitionsRoot.model_validate(raw_kpi_data)
            
            # Reconstruct the business rules structure to validate
            raw_rules_data = {
                "predefined_rules": self._predefined_rules,
                "thresholds": self._thresholds,
                "variance_drivers": self._variance_drivers,
                "flags": self._flag_decoding,
                "new_rules": self._new_rules,
                "supported_operations": self._supported_ops
            }
            BusinessRulesRoot.model_validate(raw_rules_data)
            logger.info("Configuration validation succeeded (Pydantic verified)")
        except Exception as e:
            logger.error(f"Rule Engine configuration validation failed: {e}")
            raise ValueError(f"Invalid Rule Engine configuration: {e}")


    # ── Loaders ───────────────────────────────────────────────────────────────

    @staticmethod
    def _load_json(path: Path) -> dict:
        if not path.exists():
            logger.warning(f"Rules file not found: {path}")
            return {}
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)

    @staticmethod
    def _load_yaml_file(path: Path) -> dict:
        if not path.exists():
            logger.warning(f"Rules file not found: {path}")
            return {}
        with open(path, "r", encoding="utf-8") as f:
            return yaml.safe_load(f) or {}

    # ── Business Rule Evaluation ──────────────────────────────────────────────

    def evaluate_rules(self, kpi_name: str, actual_value: float) -> list[dict]:
        """
        Evaluate all predefined + new rules against a KPI value.
        Returns list of triggered rules (severity, interpretation, action).

        Example:
            evaluate_rules('loss_ratio', 105.0)
            → [{'id': 'BR001', 'severity': 'critical', 'interpretation': '...'}]
        """
        triggered = []
        all_rules = self._predefined_rules + self._new_rules
        for rule in all_rules:
            if rule.get("kpi") not in (kpi_name, "any"):
                continue
            condition = rule.get("condition", "")
            try:
                # Replace kpi column reference with actual value
                safe_condition = (
                    condition
                    .replace(f"{kpi_name}_actual", str(actual_value))
                    .replace(f"{kpi_name}", str(actual_value))
                )
                if _safe_eval(safe_condition):
                    triggered.append({
                        "rule_id":       rule.get("id"),
                        "rule_name":     rule.get("name"),
                        "severity":      rule.get("severity"),
                        "interpretation":rule.get("interpretation"),
                        "action":        rule.get("action"),
                        "category":      rule.get("category"),
                    })
            except Exception:
                pass  # Skip rules that can't be evaluated
        triggered.sort(key=lambda r: {"critical": 0, "warning": 1, "healthy": 2}.get(r["severity"], 3))
        if triggered:
            logger.info(f"Rules triggered for '{kpi_name}'={actual_value}: "
                        f"{[r['rule_id'] for r in triggered]}")
        return triggered

    def get_threshold(self, kpi_name: str, level: str = "warning") -> float | None:
        """
        Return threshold value for a KPI at a given severity level.
        Levels: 'healthy', 'warning', 'critical', 'breakeven', 'adequate'
        """
        return self._thresholds.get(kpi_name, {}).get(level)

    def get_all_thresholds(self, kpi_name: str) -> dict:
        """Return all thresholds for a KPI."""
        return self._thresholds.get(kpi_name, {})

    def get_predefined_rules(self, category: str | None = None) -> list[dict]:
        """Return all predefined rules, optionally filtered by category."""
        if category:
            return [r for r in self._predefined_rules if r.get("category") == category]
        return self._predefined_rules

    def add_new_rule(self, rule: dict) -> bool:
        """
        Add a new rule dynamically (called by Knowledge Update Tool).
        Validates structure, appends to new_rules, persists to YAML.

        Required fields: id, name, category, kpi, condition, interpretation, severity, action
        """
        required = {"id", "name", "category", "kpi", "condition", "interpretation", "severity", "action"}
        if not required.issubset(set(rule.keys())):
            missing = required - set(rule.keys())
            logger.warning(f"New rule rejected — missing fields: {missing}")
            return False
        if rule["severity"] not in ("healthy", "warning", "critical"):
            logger.warning(f"New rule '{rule['id']}' rejected — invalid severity")
            return False
        # Check for duplicate IDs
        existing_ids = {r.get("id") for r in self._predefined_rules + self._new_rules}
        if rule["id"] in existing_ids:
            logger.warning(f"Rule ID '{rule['id']}' already exists — skipping")
            return False
        self._new_rules.append(rule)
        self._persist_new_rules()
        logger.info(f"New rule '{rule['id']}' added and persisted to business_rules.yml")
        return True

    def _persist_new_rules(self):
        """Write updated new_rules back to config/business_rules.yml."""
        try:
            with open(self._business_rules_path, "r", encoding="utf-8") as f:
                full_config = yaml.safe_load(f) or {}
            full_config["new_rules"] = self._new_rules
            with open(self._business_rules_path, "w", encoding="utf-8") as f:
                yaml.dump(full_config, f, default_flow_style=False, allow_unicode=True)
            logger.info(f"business_rules.yml updated: {len(self._new_rules)} dynamic rules")
        except Exception as e:
            logger.error(f"Failed to persist new rules: {e}")

    # ── Variance Drivers ──────────────────────────────────────────────────────

    def get_variance_driver_description(self, driver: str) -> str:
        """Return description of a variance driver from YAML config."""
        info = self._variance_drivers.get(driver, {})
        return info.get("description", f"Unknown driver: {driver}")

    def get_flag_description(self, flag_column: str, value: str) -> str:
        """Decode a flag value (e.g. structural_vs_timing_flag='S')."""
        return self._flag_decoding.get(flag_column, {}).get(value, value)

    # ── KPI Lookup ────────────────────────────────────────────────────────────

    def get_kpi(self, kpi_name: str) -> dict | None:
        """
        Look up a KPI definition by name or abbreviation.
        Returns None if not found — triggers Knowledge Update Tool.
        """
        # Direct match
        key = kpi_name.lower().replace(" ", "_").replace("-", "_")
        if key in self._kpis:
            return {"key": key, **self._kpis[key]}

        # Abbreviation match
        for k, v in self._kpis.items():
            if v.get("abbreviation", "").upper() == kpi_name.upper():
                return {"key": k, **v}

        # Partial label match
        for k, v in self._kpis.items():
            if kpi_name.lower() in v.get("label", "").lower():
                return {"key": k, **v}

        logger.warning(f"KPI not found in Rule Engine: '{kpi_name}'")
        return None

    def list_kpis(self) -> list[str]:
        """Return all available KPI keys."""
        return list(self._kpis.keys())

    def get_kpi_columns(self, kpi_name: str) -> dict:
        """Return the actual/budget/prior_year column names for a KPI."""
        kpi = self.get_kpi(kpi_name)
        if not kpi:
            return {}
        return {
            "actual":     kpi.get("actual_column"),
            "budget":     kpi.get("budget_column"),
            "prior_year": kpi.get("prior_year_column"),
            "ytd_actual": kpi.get("ytd_actual_column"),
            "ytd_budget": kpi.get("ytd_budget_column"),
        }

    def get_kpi_threshold(self, kpi_name: str) -> dict:
        """Return threshold rules for a KPI if available."""
        kpi = self.get_kpi(kpi_name)
        return kpi.get("thresholds", {}) if kpi else {}



    # ── Drill-Down Hierarchy ──────────────────────────────────────────────────

    def get_hierarchy(self, dimension_type: str) -> dict:
        """
        Return the drill-down levels for a dimension type.
        Types: 'geographic', 'temporal', 'business', 'customer', 'distribution', 'risk'
        """
        return self._hierarchy.get(dimension_type, {})

    def get_drill_down_column(self, dimension_type: str, level: int) -> str | None:
        """Return the column name for a specific drill-down level."""
        hierarchy = self.get_hierarchy(dimension_type)
        return hierarchy.get(f"level_{level}")

    def find_dimension_type(self, column: str) -> str | None:
        """Given a column name, find which dimension type it belongs to."""
        for dim_type, levels in self._hierarchy.items():
            if column in levels.values():
                return dim_type
        return None

    # ── Rule Update (called by Knowledge Update Tool) ─────────────────────────

    def add_kpi(self, key: str, definition: dict) -> bool:
        """
        Add a new KPI to the in-memory store and persist to disk.
        Only called by the Knowledge Update Tool after validation.
        """
        if key in self._kpis:
            logger.warning(f"KPI '{key}' already exists — skipping add")
            return False

        # Validate candidate KPI definition using Pydantic
        from app.services.schemas import KPIDefinition
        try:
            KPIDefinition.model_validate(definition)
        except Exception as e:
            logger.error(f"Failed to validate new KPI '{key}': {e}")
            raise ValueError(f"Invalid KPI definition structure: {e}")

        self._kpis[key] = definition
        # Persist
        all_data = {"kpis": self._kpis}
        with open(self._kpi_definitions_path, "w", encoding="utf-8") as f:
            json.dump(all_data, f, indent=2)
        logger.info(f"New KPI added to Rule Engine: '{key}'")
        return True
